inputstream.adaptive/addon.xml.in, src/main.cpp
The for xbmc/xbmc#12011 needed addon changes.
=> Remove not used part

CMakeLists.txt, inputstream.adaptive/addon.xml.in
Related to kodi Pull Request xbmc/xbmc#12029
Not merge in before is in Kodi!
=> change to automatic depends set on addon.xml

README.md, inputstream.adaptive/addon.xml.in, wvdecrypter/wvdecrypter.cpp, wvdecrypter/wvdecrypter_android.cpp
@peak3d this fixes my issue. is it acceptable ?
=> [jsmn] increase tokens size to 256

src/main.cpp, wvdecrypter/wvdecrypter.cpp
=> wvdecrypter fixes

src/main.cpp
Rename required after https://github.com/xbmc/xbmc/pull/12780 is merged
=> Rename GetProperty to GetPropertyValue

src/oscompat.cpp, wvdecrypter/cdm/base/native_library_win.cc
=> win10: fix deprecated api

wvdecrypter/cdm/build/build_config.h
=> win10: fix arm build

depends/common/expat/expat.txt, depends/windows/expat/0001-disable-docs.patch, depends/windows/expat/expat.txt
compile tested for android, ios (+ tvos), osx & windows
=> [depends] bump expat to 2.2.5

depends/windows/expat/0002-uwp.patch
#114 broke uwp as expat added some function calls not supported on uwp.
=> [depends][windows] fix expat for uwp

CMakeLists.txt, appveyor.yml
=> [appveyor] add WindowsStore 

.gitattributes
=> added .gitattributes to avoid the issue with LE for patches and diffs.

src/parser/TTML.cpp
Hello,
I fixed three bugs in the TTML parser:
1)Ignore newline characters in subtitle text if present in TTML: https://github.com/peak3d/inputstream.adaptive/issues/214
2) Support for 3 digit fractional seconds in begin and end attributes, for example:
```XML
<?xml version="1.0" encoding="utf-8"?><tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="dut"><head><metadata><ttm:title></ttm:title><ttm:desc></ttm:desc><ttm:copyright></ttm:copyright></metadata><styling><style xml:id="bold" tts:fontWeight="bold" /><style xml:id="italic" tts:fontStyle="italic" /><style xml:id="underline" tts:textDecoration="underline" /><style xml:id="speakerStyle" …
```
=> fixed some bugs in TTML parser

CMakeLists.txt, depends/common/expat/CMakeLists.txt, lib/libbento4/CMakeLists.txt, lib/mpegts/CMakeLists.txt, lib/webm_parser/CMakeLists.txt, wvdecrypter/CMakeLists.txt, wvdecrypter/jni/CMakeLists.txt
Only related to Leia and planned Kodi request to update addon depends check!
=> update CMakeLists.txt to 3.5

inputstream.adaptive/resources/language/resource.language.es_es/strings.po
Hi @peak3d, I have translated the add-on for Spanish.
=> Creation Spanish language

inputstream.adaptive/resources/language/resource.language.fr_fr/strings.po
=> Add french translate

inputstream.adaptive/resources/language/resource.language.it_it/strings.po
=> Added Italian language

inputstream.adaptive/resources/language/resource.language.pl_pl/strings.po
=> Add PL translation

src/helpers.cpp
I am sorry but i see only today that i pushed the wrong commit on previous pr
=> Fixed nextEmpty on replaceAll

inputstream.adaptive/resources/language/resource.language.el_gr/strings.po
& fill blank strings with the same values to avoid errors on check scripts
=> Filled #30161 (greek)

inputstream.adaptive/resources/language/resource.language.ro_ro/strings.po
Added initial translation for Romanian language
=> Added Romanian strings
