- inputstream.adaptive/addon.xml.in
- src/common/AdaptiveStream.cpp
- src/common/AdaptiveStream.h
- src/common/AdaptiveTree.cpp
- src/common/AdaptiveTree.h
- src/helpers.cpp
- src/helpers.h
- src/main.cpp
- src/main.h
- src/parser/DASHTree.cpp
- src/parser/SmoothTree.cpp
Hi @peak3d 
This fixes #20. I'm *very* new to c++ so I don't know if this implementation is a good way of going about it particularly because it relies on a global variable, but it works nonetheless.
> Send custom headers with segment downloads

- src/parser/SmoothTree.cpp
I've got ism manifests where TimeScale parameter is omitted,
according to https://msdn.microsoft.com/en-us/library/ee673438 it is optional
and should default to 10000000 if omitted
this fixes an issue where it's impossible to seek with such manifests
> [fix] set default TimeScale

- wvdecrypter/cdm/base/native_library_win.cc
This PR fixes CDM library loading error on Windows if path contains unicode characters:
```
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\ユーザー\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
```
Use UTF8->Unicode conversion.
> [Win] Fix CDM library loading error if path contains unicode characters

- src/parser/DASHTree.cpp
Seems that it is not mandatory to specify the timescale.
For example this stream does not use it:
http://www-itec.aau.at/~cmueller/libdashtest/showcases/big_buck_bunny_480.mpd
Facing some issues with this one
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd
> Setting default timescale to 1

- lib/libbento4/Codecs/Ap4AvcParser.cpp
inputstream.adaptive.5c9c7f2/lib/libbento4/Codecs/Ap4AvcParser.cpp:968:1: warning: control reaches end of non-void function [-Wreturn-type]
Signed-off-by: Olaf Hering <olaf@aepfle.de>
> fix return code of ParseFrameForSPS

- inputstream.adaptive/resources/settings.xml.in
It appears that the enumeration was not 100% the same in the settings causing 720p to be 640p, and 1080p to be 720p.
This fixes #237 and pietje666/plugin.video.vrt.nu#195
> Fix issue where 1080p means 720p

- src/parser/HLSTree.cpp
While reading this part of the code I was wondering why it wasn't made somewhat easier.
Also, why do we return an empty string for Video, and default to AAC for Audio ?
> Simplify decision tree

- src/parser/TTML.cpp
- src/parser/TTML.h
fixed ttml subtitles problem on windows, fixes https://github.com/peak3d/inputstream.adaptive/issues/247:
- fixed sscanf problem on Windows with fraction after delimiter
- added support for frames in timeExpression
> fixed ttml subtitles problem, peak3d/inpustream.adaptive#247

- src/common/AdaptiveStream.cpp
- src/common/AdaptiveTree.h
While trying to create a Kodi addon for Rakuten I got several times a segmentation fault for some videos. It turned out that the MPD of the crashing ones was different then for the working ones.
In the crashing ones they use in SegmentURL elements both "media" and "mediaRange" attribute at the same time. 
Therefore I adjusted Segment structure to keep both attributes at the same time. In addition to that the range header handling was added for that case too.
Additional side-effect is that it fixes this issue with the Youtube addon:
https://github.com/jdf76/plugin.video.youtube/issues/595
I don't know if those audio streams are using the same structure like Rakuten but at least no I have sound there as well.
> Fix SegFault on SegmentURL handling

- src/parser/TTML.cpp
- src/parser/TTML.h
@peak3d 
This pull request fixes the following bug:
- When there are multiple `<span>` tags inside a ttml `<p>` tag, the TTML parser treats this as multiple subtitle lines. This is wrong behaviour. This bug causes subtitles to break at unintended positions or causes that an extra unwanted empty line is added when a `<br>` tag is present between two or more `<span>` tags.
Multiple `<span>` tags inside a `<p>` tag should be treated as a single subtitle line, only a `<br>` tag can break a subtitle line. This pull request fixes this.
**Example TTML fragment**
```xml
<p begin="00:04:15.613" end="00:04:20.253" region="region-10" tts:textAlign="center">
<span style="singleHeightStyle" xml:space="preserve" tts:color="yellow" tts:backgroundColor="black">Dat wil zeggen dat het ontegen- …
```
> support multiple span tags in ttml

- src/common/AdaptiveTree.h
- src/main.cpp
- src/parser/DASHTree.cpp
Some streaming servers use MPD Location tag redirects for statistics or tracking purposes.
For instance:
```xml
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="urn:mpeg:dash:schema:mpd:2011"
xmlns:xlink="http://www.w3.org/1999/xlink"
xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
profiles="urn:mpeg:dash:profile:isoff-live:2011"
type="dynamic"
availabilityStartTime="1970-01-01T00:00:00Z"
publishTime="2019-08-08T07:57:22"
minimumUpdatePeriod="PT10S"
suggestedPresentationDelay="PT10S"
minBufferTime="PT10S">
<Location>https://dcs-live.apis.anvato.net/server/play/kZEoafO6xdBCB8JJd/manifest.mpd?anvsid=xxxxxxxxxx-xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx …
```
> add support for mpd location redirects

- src/common/AdaptiveTree.h
- src/parser/DASHTree.cpp
This includes:
- add presentationTimeOffset and startNumber SegmentList attributes
- startPTS_ handling for SegmentList based streams
- This fixes https://github.com/peak3d/inputstream.adaptive/issues/288
> add support for anvato livestreams

- wvdecrypter/wvdecrypter_android.cpp
Currently this non-error message "Key system request" is being logged as an error.
This pull request simply changes it to a debug message instead
```
2019-08-25 13:29:54.052 T:17933   DEBUG: AddOnLog: InputStream Adaptive: WVDecrypter JNI, SDK version: 25, class: org/xbmc/kodi
2019-08-25 13:29:54.062 T:17933   DEBUG: AddOnLog: InputStream Adaptive: WVDecrypter constructed
2019-08-25 13:29:54.062 T:17933   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
2019-08-25 13:29:54.062 T:17933   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /data/app/org.xbmc.kodi-1/lib/arm/libssd_wv.so
2019-08-25 13:29:54.063 T:17933   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
```
> Log Debug "Android key system request" (instead of Error)

- src/common/AdaptiveTree.h
- src/main.cpp
- src/parser/DASHTree.cpp
With the last changes made in branch, the properties of the subtitles have been broken, caused by a double identical condition, fixed this, i also introduced two new things:
- added "forced" property to adaptationset
this allow to set more than one property flag to a single subtitle stream (see screenshot, more properties splitted by comma)
- support to "impaired" property
allow to set a subtitle as for impaired people
Tested on Windows with latest Kodi 18 and NF add-on
> Fixed and improved subtitle properties

- src/helpers.cpp
- src/helpers.h
- src/parser/WebVTT.cpp
I had to change the identification of encoding strings, unfortunately here you have set the search from the beginning of the string, and this does not work in all cases
this is an example of a netflix arab subtitle string:
`<c.arabic>&lrm;‏‎.‎لست جباناً‎ ؟‎من يقول إنّي جبان‎‏</c.arabic>`
as you see in this case there are also tags
so you need to search not by position
~I've also added recognition of the missing escapes~
~often displayed in netflix subtitles in any language~
~I followed the example of another Webtt parser~
~that performs the replacement more or less as you implemented~
~https://github.com/caitp/webvtt~
For this wait approve of : https://github.com/xbmc/xbmc/pull/17085
it would be very much appreciated if you would also apply this fix also on Leia branch
because a lot of …
> Subtitles webvtt fixed encoding strings

- src/main.cpp
Hi @peak3d 
reader_->GetPTSDiff can return a negative number and seek to or near zero will cause the adaptivestream to download every segment available in the tree (I think it must be looking for the right PTS?), playback pauses until this has finished and hangs on pressing the stop key.
I'm not sure this is an issue for fmp4 but definitely for ts streams.
Stream used for testing:
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
```
You can reproduce by starting the stream and pressing down (seeking backwards by pressing left doesn't allow you to easily seek to zero)
Thanks to @matthuisman for finding and investigating this issue
> Ensure seeking to zero does not wrap around

- src/main.cpp
Hi @peak3d
I noticed in my testing for #374 that manually choosing another stream during playback causes a crash (m_IncludedStreams[2] for eg. would be 1007) - this PR addresses that.
> Fix for manual stream changing

- src/helpers.cpp
- src/helpers.h
- src/parser/WebVTT.cpp
When netflix assigns some style to the text it also includes the orientation string, unfortunately the previous fix does not remove the remaining encodings string
Example:
`<c.bg_transparent><i>&lrm;Mândrie și prejudecată,</i></c.bg_transparent><c.bg_transparent>&lrm; nu?</c.bg_transparent>`
Locke & Key Season 1 ep.4
In this case it should be maintained only at the beginning and the others removed
After the fix:
> WebVTT fix for multiple rlm lrm in the same string

- src/common/AdaptiveTree.h
- src/parser/HLSTree.cpp
- src/parser/HLSTree.h
Hi @peak3d 
The #EXT-X-DISCONTINUITY tags are handled this way:
* Close off the current representation (freeSegments, swap newsegments etc.) and set period duration
* Add a new period (re-use master manifest to set up) if there isn't one already from preparation of other representations
* use the index of our current rep/adp to ensure we keep working on the same rep in the new period
Apologies for the large diff.
With HLS a 'period' differs from DASH since it is defined within a representation/adaptationset, therefore each period should contain an identical amount of adaptationsets with an identical amount of representations. So my solution is to copy the adaptationset/representations to each new period.
I thought the easiest and safest way to deep-copy the periods is to just re-parse the …
> [HLS] EXT-X-DISCONTINUITY (multiple periods)

- inputstream.adaptive/resources/language/resource.language.de_de/strings.po
- inputstream.adaptive/resources/language/resource.language.el_gr/strings.po
- inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
- inputstream.adaptive/resources/language/resource.language.es_es/strings.po
- inputstream.adaptive/resources/language/resource.language.fr_fr/strings.po
- inputstream.adaptive/resources/language/resource.language.hr_hr/strings.po
- inputstream.adaptive/resources/language/resource.language.hu_hu/strings.po
- inputstream.adaptive/resources/language/resource.language.it_it/strings.po
- inputstream.adaptive/resources/language/resource.language.ja_JP/strings.po
- inputstream.adaptive/resources/language/resource.language.ko_KR/strings.po
- inputstream.adaptive/resources/language/resource.language.nl_nl/strings.po
- inputstream.adaptive/resources/language/resource.language.pl_pl/strings.po
- inputstream.adaptive/resources/language/resource.language.ru_ru/strings.po
- inputstream.adaptive/resources/language/resource.language.sv_se/strings.po
This PR includes:
- Translations for strings that were expected to be identical
- Add missing strings to most languages
- Translate untranslated strings for Dutch
- Remove BOM from Russian translation
- Fix syntax errors in French translation
- Remove unused/incorrect English `msgstr` entries
> Various translation fixes

- src/parser/HLSTree.cpp
- src/parser/HLSTree.h
Hi @peak3d 
This will address #353 
A test strm: 
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://cwip-shaka-proxy.appspot.com/no_auth||R{SSM}|
https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8
```
As part of these changes EXT-X-MAP and EXT-X-KEY values now persist into the next period/discontinuity as this is a requirement in HLS spec. The test stream above requires this as the first two segments are in clear, then the encryption begins. There is a discontinuity tag however the initialization segment remains the same - there is no new map tag.
The EXT-X-SESSION-KEY in the master manifest will …
> HLS Widevine

- .gitignore
- inputstream.adaptive/addon.xml.in
- src/main.cpp
Minor API update to remove 2 unused function calls, modify PauseStream signature and increase num stream properties allowed in inputstream addons.
Kodi PR: https://github.com/xbmc/xbmc/pull/17620
Do not merge yet.
> Matrix Inputstream API change to v2.1.0 - Adaptive version 2.5.5
